# Generated by Django 4.2 on 2024-09-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hits',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
