# Generated by Django 4.2 on 2024-09-13 05:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_alter_comments_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='non_recommendation',
            field=models.ManyToManyField(related_name='%(class)s_non_recommend', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='recommendation',
            field=models.ManyToManyField(related_name='%(class)s_recommend', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='non_recommendation',
            field=models.ManyToManyField(related_name='%(class)s_non_recommend', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='recommendation',
            field=models.ManyToManyField(related_name='%(class)s_recommend', to=settings.AUTH_USER_MODEL),
        ),
    ]
