# Generated by Django 4.2 on 2024-09-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
