# Generated by Django 4.2 on 2024-09-12 04:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0005_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='non_recommendation',
            field=models.ManyToManyField(related_name='non_recommend_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='recommendation',
            field=models.ManyToManyField(related_name='recommend_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
